version: '3'

services:
  web:
    container_name: web
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    image: php:fpm
    command: bash -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install"
    volumes:
      - ./src:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
